export const assessmentQuestions = [
  // Depression (1-14)
  { id: 1, text: "I felt that I had nothing to look forward to", domain: "depression" },
  { id: 2, text: "I couldn’t seem to experience any positive feeling", domain: "depression" },
  { id: 3, text: "I felt downhearted and sad", domain: "depression" },
  { id: 4, text: "I felt I wasn’t worth much", domain: "depression" },
  { id: 5, text: "I had difficulty motivating myself", domain: "depression" },
  { id: 6, text: "I blamed myself unnecessarily", domain: "depression" },
  { id: 7, text: "I felt hopeless about the future", domain: "depression" },
  { id: 8, text: "I lost interest in things I usually enjoy", domain: "depression" },
  { id: 9, text: "I felt life was meaningless", domain: "depression" },
  { id: 10, text: "I had thoughts of ending my life", domain: "depression" },
  { id: 11, text: "I had trouble sleeping", domain: "depression" },
  { id: 12, text: "I felt like crying frequently", domain: "depression" },
  { id: 13, text: "I found it difficult to concentrate", domain: "depression" },
  { id: 14, text: "I felt like a failure", domain: "depression" },
  // Anxiety (15-28)
  { id: 15, text: "I felt scared without reason", domain: "anxiety" },
  { id: 16, text: "I felt shaky or trembly", domain: "anxiety" },
  { id: 17, text: "I had difficulty breathing", domain: "anxiety" },
  { id: 18, text: "I feared the worst happening", domain: "anxiety" },
  { id: 19, text: "I felt my heart pounding", domain: "anxiety" },
  { id: 20, text: "I had a fear of losing control", domain: "anxiety" },
  { id: 21, text: "I felt nervous or 'on edge'", domain: "anxiety" },
  { id: 22, text: "I experienced dizziness or faintness", domain: "anxiety" },
  { id: 23, text: "I had nausea or stomach upset", domain: "anxiety" },
  { id: 24, text: "I found it hard to relax", domain: "anxiety" },
  { id: 25, text: "I felt I was close to panic", domain: "anxiety" },
  { id: 26, text: "I experienced numbness or tingling", domain: "anxiety" },
  { id: 27, text: "I had fear of dying", domain: "anxiety" },
  { id: 28, text: "I avoided situations that might trigger anxiety", domain: "anxiety" },
  // Stress (29-42)
  { id: 29, text: "I found it hard to wind down", domain: "stress" },
  { id: 30, text: "I tended to over-react", domain: "stress" },
  { id: 31, text: "I found myself getting agitated easily", domain: "stress" },
  { id: 32, text: "I felt that I was using a lot of nervous energy", domain: "stress" },
  { id: 33, text: "I felt impatient or irritable", domain: "stress" },
  { id: 34, text: "I felt everything was too much", domain: "stress" },
  { id: 35, text: "I found it hard to cope", domain: "stress" },
  { id: 36, text: "I had trouble managing responsibilities", domain: "stress" },
  { id: 37, text: "I felt touchy or easily upset", domain: "stress" },
  { id: 38, text: "I had sudden mood swings", domain: "stress" },
  { id: 39, text: "I felt I was always 'on guard'", domain: "stress" },
  { id: 40, text: "I found it difficult to slow down", domain: "stress" },
  { id: 41, text: "I was intolerant of interruptions", domain: "stress" },
  { id: 42, text: "I had difficulty staying calm", domain: "stress" }
]; 